build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - wget https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2
    - tar jxf boost_1_67_0.tar.bz2
    - cd boost_1_67_0
    - ./bootstrap.sh
    - ./b2 --with-context cxxflags=-std=c++14 address-model=$$arch
    - cd ../benchmark
    - make CXXFLAGS="-DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -I../boost_1_67_0 -L../boost_1_67_0/stage/lib" LDFLAGS="-lboost_context-mgw54-mt-x$$arch-1_67"

matrix:
  arch:
    - 64
    - 32
